# Generated by Django 4.2.2 on 2023-06-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stormrage', '0002_fraction_alter_alpha_content_alpha_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alpha',
            options={'ordering': ['title'], 'verbose_name': 'Warcraft heroes', 'verbose_name_plural': 'Warcraft heroes'},
        ),
        migrations.AlterModelOptions(
            name='fraction',
            options={'ordering': ['name'], 'verbose_name': 'Fractions', 'verbose_name_plural': 'Fractions'},
        ),
        migrations.AlterField(
            model_name='alpha',
            name='content',
            field=models.TextField(verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='alpha',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='alpha',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='fraction',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Fraction'),
        ),
    ]
